import { Navigate, useParams } from 'react-router-dom'
import { useEffect, useMemo, useState } from 'react'
import HpnyCard from '../../components/HpnyCard/HpnyCard'
import HpnyCardMobile from '../../components/HpnyCard/HpnyCardMobile'
import type { HpnyCardContent } from './hpnyContent'

// Encoded HPNY_CONTENT (base64)
const ENCODED_CONTENT =
	'eyI0aG00ZC0yMDI2Ijp7InJlY2VpdmVySWQiOiI0aG00ZC0yMDI2IiwicmVjZWl2ZXJEaXNwbGF5TmFtZSI6IkFobWFkIiwiY292ZXJUaXRsZSI6IkhhcHB5IE5ldyBZZWFyISIsImNvdmVyU3VidGl0bGUiOiJBIHNtYWxsIGNhcmQganVzdCBmb3IgeW91IiwiaW5zaWRlVGl0bGUiOiIiLCJpbnNpZGVCb2R5IjoiRGVhciBBaG1hZCxcblxuSGFwcHkgbmV3IHllYXIhIVxuXG5JIHdpc2ggeW91IGFub3RoZXIgeWVhciBmdWxsIG9mIGhlYWx0aCBhbmQgaGFwcGluZXNzIHdpdGggeW91ciBmYW1pbHkuXG5cbkkgYWxzbyB3YW50IHRvIHRha2UgdGhpcyBvcHBvcnR1bml0eSB0byB0aGFuayB5b3UgZm9yIHlvdXIgc3VwcG9ydCB3aXRoIE9ESSBhbmQgYSBsb3QgbW9yZSBhdCB3b3JrLiBIZXJlIHRvIGFub3RoZXIgYXdlc29tZSB5ZWFyIHdvcmtpbmcgdG9nZXRoZXIg8J+knPCfpJshIiwic2lnbmF0dXJlIjoiQmVzdCIsImltYWdlcyI6WyJmdy5qcGciLCJncmlmMS5qcGciXX0sIkRpa3NoYTI2Ijp7InJlY2VpdmVySWQiOiJEaWtzaGEiLCJyZWNlaXZlckRpc3BsYXlOYW1lIjoiRGlrc2hhIiwiY292ZXJUaXRsZSI6IkhhcHB5IE5ldyBZZWFyISIsImNvdmVyU3VidGl0bGUiOiJBIHNtYWxsIGNhcmQganVzdCBmb3IgeW91IiwiaW5zaWRlVGl0bGUiOiIiLCJpbnNpZGVCb2R5IjoiRGVhciBEaWtzaGEsXG5cbkhhcHB5IG5ldyB5ZWFyISFcblxuSSB3aXNoIHlvdSBhbm90aGVyIHllYXIgZnVsbCBvZiBoZWFsdGggYW5kIGhhcHBpbmVzcyB3aXRoIHlvdXIgaHViYnkgYW5kIGZhbWlseS5cblxuVGhhbmsgeW91IGZvciBoZWxwaW5nIG1lIHBlcnNvbmFsbHkgYW5kIHRoZSB0ZWFtIG9uIG11bHRpcGxlIGZyb250cy4gRnJvbSBqdXN0IHNob3J0IDMgbW9udGhzLCBJJ3ZlIHNlZW4geW91IGJyaW5nIGEgdG9uIG9mIHZhbHVlcyB0byB0aGUgdGVhbSBhbmQgSSBkbyBhZG1pcmUgdGhhdC4gSGVyZSB0byBhbm90aGVyIGF3ZXNvbWUgeWVhciB3b3JraW5nIHRvZ2V0aGVyIPCfpJzwn6SbISIsInNpZ25hdHVyZSI6IkJlc3QiLCJpbWFnZXMiOlsiZncuanBnIiwiZ3JpZjEuanBnIl19LCJhbHYxbiI6eyJyZWNlaXZlcklkIjoiYWx2MW4iLCJyZWNlaXZlckRpc3BsYXlOYW1lIjoiQWx2aW4iLCJjb3ZlclRpdGxlIjoiSGFwcHkgTmV3IFllYXIhIiwiY292ZXJTdWJ0aXRsZSI6IkEgc21hbGwgY2FyZCBqdXN0IGZvciB5b3UiLCJpbnNpZGVUaXRsZSI6IiIsImluc2lkZUJvZHkiOiJEZWFyIEFsdmluLFxuXG5IYXBweSBuZXcgeWVhciEhXG5cbkkgd2lzaCB5b3UgYW5vdGhlciB5ZWFyIGZ1bGwgb2YgaGVhbHRoIGFuZCBoYXBwaW5lc3Mgd2l0aCB5b3VyIGZhbWlseS5cblxuSSB3YW50IHRvIHRha2UgdGhpcyBvcHBvcnR1bml0eSB0byB0aGFuayB5b3UgZm9yIHRydXN0aW5nIG1lLCBsZXR0aW5nIG1lIGJlIGEgcGFydCBvZiB0aGlzIGFtYXppbmcgdGVhbSBhbmQgZm9yIHRoZSB0cmVtZW5kb3VzIHN1cHBvcnQgeW91J3ZlIGJlZW4gcHJvdmlkaW5nLiBIZXJlIHRvIGFub3RoZXIgYXdlc29tZSB5ZWFyIHdvcmtpbmcgdG9nZXRoZXIg8J+knPCfpJshIiwic2lnbmF0dXJlIjoiQmVzdCIsImltYWdlcyI6WyJmdy5qcGciLCJncmlmMS5qcGciXX0sImphc3NpZTI2Ijp7InJlY2VpdmVySWQiOiJqYXNzaWUyNiIsInJlY2VpdmVyRGlzcGxheU5hbWUiOiJKYXNzaWUiLCJjb3ZlclRpdGxlIjoiSGFwcHkgTmV3IFllYXIhIiwiY292ZXJTdWJ0aXRsZSI6IkEgc21hbGwgY2FyZCBqdXN0IGZvciB5b3UiLCJpbnNpZGVUaXRsZSI6IiIsImluc2lkZUJvZHkiOiJEZWFyIEphc3NpZSxcblxuSGFwcHkgbmV3IHllYXIhIVxuXG5JIHdpc2ggeW91IGFub3RoZXIgeWVhciBmdWxsIG9mIGhlYWx0aCBhbmQgaGFwcGluZXNzIHdpdGggeW91ciBiaWcgZmFtaWx5LlxuXG5JIHdhbnQgdG8gdGFrZSB0aGlzIG9wcG9ydHVuaXR5IHRvIHRoYW5rIHlvdSBmb3IgeW91ciBsZWFkZXJzaGlwLCBmb3IgdHJ1c3RpbmcgbWUgYW5kIGxldHRpbmcgbWUgYmUgYSBwYXJ0IG9mIHRoZSB0ZWFtLlxuXG5IZXJlIHRvIGEgbmV3IGZydWl0ZnVsIHllYXIhIiwic2lnbmF0dXJlIjoiQmVzdCIsImltYWdlcyI6WyJmdy5qcGciLCJncmlmMS5qcGciXX0sImFudGhvbnkxMjYiOnsicmVjZWl2ZXJJZCI6ImFudGhvbnkxMjYiLCJyZWNlaXZlckRpc3BsYXlOYW1lIjoiQW50aG9ueSIsImNvdmVyVGl0bGUiOiJIYXBweSBOZXcgWWVhciEiLCJjb3ZlclN1YnRpdGxlIjoiQSBzbWFsbCBjYXJkIGp1c3QgZm9yIHlvdSIsImluc2lkZVRpdGxlIjoiIiwiaW5zaWRlQm9keSI6IkRlYXIgQW50aG9ueSxcblxuSGFwcHkgbmV3IHllYXIhIVxuXG5JIHdpc2ggeW91IGFuZCB5b3VyIGZhbWlseSBhbm90aGVyIHllYXIgZnVsbCBvZiBoZWFsdGggYW5kIGhhcHBpbmVzcy4gQW5kIEkgd2lzaCBldmVyeXRoaW5nIHdvdWxkIGdvIHdlbGwgd2l0aCB5b3VyIGRhdWdodGVyJ3MgdHJlYXRtZW50LCBwbGVhc2UgbGV0IG1lIGtub3cgaWYgSSBjYW4gaGVscCB5b3UgaW4gYW55IHdheSwgSSBkbyBrbm93IFZpZXRuYW0gYWxzbyBoYXMgdmVyeSBpZiBub3QgbW9yZSBjYXBhYmxlIGRvY3RvcnMuXG5cbkFuZCwgdGhhbmsgeW91IGZvciBsZWFkZXJzaGlwLCBmb3IgdHJ1c3RpbmcgbWUgYW5kIGxldHRpbmcgbWUgYmUgYSBwYXJ0IG9mIHRoaXMgd29uZGVyZnVsIHRlYW0uIiwic2lnbmF0dXJlIjoiQmVzdCIsImltYWdlcyI6WyJmdy5qcGciLCJncmlmMi5qcGciXX0sImx1Y2l1c0NhcCI6eyJyZWNlaXZlcklkIjoibHVjaXVzQ2FwIiwicmVjZWl2ZXJEaXNwbGF5TmFtZSI6IlZpbmgiLCJjb3ZlclRpdGxlIjoiSGFwcHkgTmV3IFllYXIhIiwiY292ZXJTdWJ0aXRsZSI6IlRvIGdyZWF0bmVzcyBhbmQgcHJvc3Blcml0eSIsImluc2lkZVRpdGxlIjoiIiwiaW5zaWRlQm9keSI6IkhleSBWaW5oLFxuXG5IYXBweSBuZXcgeWVhciB0byB5b3UgYW5kIHlvdXIgZmFtaWx5IVxuXG5JIHdpc2ggeW91IGFuZCBMdWNpdXMgQ2FwaXRhbCBhbm90aGVyIHByb3NwZXJvdXMgeWVhciB3aXRoIGdyZWF0ZXIgYWNoaWV2ZW1lbnRzIGFuZCBzdWNjZXNzZXMuIEFuZCB0aGFuayB5b3UgZm9yIHRoZSBmcmllbmRzaGlwLCB0aGUgcGFydG5lcnNoaXAsIHRoZSBjYXIocykgYW5kIHdoYXRldmVyIGVsc2UgdGhlcmUgaXMhXG5cbkp1c3QgYXMgaW1wb3J0YW50bHksIHRha2UgZ29vZCBjYXJlIG9mIHlvdXIgaGVhbHRoIGFuZCBleGVyY2lzZSBtb3JlIHNpci4iLCJzaWduYXR1cmUiOiJCZXN0IiwiaW1hZ2VzIjpbInZpbmgxLmpwZyIsInZpbmgzLmpwZyJdfSwibmEtY29tLW5hbSI6eyJyZWNlaXZlcklkIjoibmEtY29tLW5hbSIsInJlY2VpdmVyRGlzcGxheU5hbWUiOiJOaW5hIiwiY292ZXJUaXRsZSI6IkhhcHB5IE5ldyBZZWFyISIsImNvdmVyU3VidGl0bGUiOiJn4butaSB04bubaSBjxqFtIG7huq9tIGPhu6dhIGFuaCIsImluc2lkZVRpdGxlIjoiIiwiaW5zaWRlQm9keSI6IkPhu6VjIGPGoW0gbuG6r20gaXUgZOG6pXUgY+G7p2EgYW5oLFxuXG5IYXBweSBuZXcgeWVhciBhbmQgaGFwcHkgMSB5ZWFyIGFyb3VuZCB0aGUgc3VuIHdpdGggeW91IVxuXG5UaGlzIHllYXIsIHdlIGJvdGggd2lsbCBuZWVkIHRvIGNoYW5nZSBmb3IgdGhlIGJldHRlci4gSSB3aWxsIG1ha2UgYSBwcm9taXNlIHRvIHlvdSB0aGF0IHdlIHdpbGwgc3BlbmQgbW9yZSBxdWFsaXR5IHRpbWUgdG9nZXRoZXIsIG5pZ2h0LXRpbWUgd2l0aG91dCBzb2NpYWwgbWVkaWEgZGlzcnVwdGlvbiwgZ3JvdyBzbWFydGVyIGVtb3Rpb25hbGx5IGFuZCBpbnRlbGxpZ2VudGx5LCB3ZWFyIGNvb2wtYXNzIG91dGZpdHMgYW5kIGdvIG9uIGEgZGF0ZS1uaWdodCBldmVyeSBtb250aC4gVGhhdCdzIHRoZSBsZWFzdCBJIGNhbiBkby5cblxuSSBvbmx5IHdpc2ggdGhhdCB0aGlzIHllYXIsIHlvdSB3aWxsIGhhdmUgbW9yZSBhdWRhY2l0eSB0byBzcGVhayB3aGF0IHlvdSB0aGluaywgZG8gd2hhdCB5b3Ugd2FudCwgZ2V0IHdoYXQgeW91IGhvcGUgZm9yIGFuZCB0YWtlIGFjdGlvbiB0byBhY2hpZXZlIHlvdXIgZ29hbHMuIE1vc3QgaW1wb3J0YW50bHksIHRoaW5rIGFib3V0IHdoYXQgeW91IHdhbnQgaW4gbGlmZSBvciB0aGlzIHllYXIsIHlvdSdyZSB5b3VuZyBzbyBjaGVyaXNoIGV2ZXJ5IHBpZWNlIG9mIHRpbWUgeW91IGhhdmUgYW5kIG1ha2UgdGhlIG1vc3Qgb2YgaXQuIEknbSBhIGd1eSBzbyBJJ20gc28gbG9naWNhbCBhYm91dCB0aGVzZSBzdHVmZnMsIEkgcGxhbiBhbmQgY2FsY3VsYXRlIGEgbG90LCBtYXliZSBhIGJpdCBvZiB0aGF0IChsb2dpY2FsLCBwbGFubmluZywgY2FsY3VsYXRpbmcpIHdpbGwgZG8gZ29vZCBmb3IgeW91ciBsaWZlLiBTbywgYW5zd2VyIHRoaXM6IFdoYXQgZG8geW91IHdhbnQgZm9yIHlvdXJzZWxmIHRoaXMgeWVhcj9cblxuVGhhbmsgeW91IGZvciBicmluZyBzbWlsZXMgdG8gbXkgZmFjZSBhbGwgdGhlIHRpbWUuIiwic2lnbmF0dXJlIjoiSSBsb3ZlIHlvdSDwn5KZIiwiaW1hZ2VzIjpbIm5hMS5qcGciLCJuYTIuanBnIl19LCJhbDRuIjp7InJlY2VpdmVySWQiOiJhbDRuIiwicmVjZWl2ZXJEaXNwbGF5TmFtZSI6IkFsYW4iLCJjb3ZlclRpdGxlIjoiSGFwcHkgTmV3IFllYXIhIiwiY292ZXJTdWJ0aXRsZSI6InRvIG15IGJyb3RoZXIiLCJpbnNpZGVUaXRsZSI6IiIsImluc2lkZUJvZHkiOiJEZWFyIEhvYW5nIEFuaCxcblxuSGFwcHkgbmV3IHllYXIgYW5kIHdlbGNvbWUgeW91IHRvIHRoZSBhZ2Ugb2YgaW5kZXBlbmRlbmNlICgxOHlvKSFcblxuWW91IGFyZSBlYXJuaW5nIHlvdXIgb3duIG1vbmV5IG5vdywgSSdtIHNvIGhhcHB5ISBMaWZlIGlzIHN0aWxsIGxvbmcgYnV0IG1ha2Ugc3VyZSB5b3UgdXNlIGl0IHdpc2VseSwgbWFrZSBwbGFucyB0byB0cmF2ZWwgYXJvdW5kIG1vcmUgKGF0IGxlYXN0IDEgbmVhciBhbmQgMSBmYXIgcGxhY2VzIGEgeWVhcikgYXMgdGhpcyBpcyB3aGF0IEkgd2lzaCBJIGhhZCBkb25lIGluIHlvdXIgYWdlLiBJIHRob3VnaHQgd2hlbiBJIGhhdmUgbW9uZXksIEkgd2lsbCB0cmF2ZWwgbW9yZSBidXQgSSBjYW4gaGFyZGx5IGZpbmQgdGhlIHRpbWUuIFNvIHllYS4uLiBtYWtlIHBsYW4gZm9yIHRyYXZlbGluZy5cblxuVHJhdmVsaW5nIGlzIG9uZSBvZiB0aGUgY2hlYXAgYWN0aW9ucyB0aGF0IHlvdSBjYW4gZG8gdG8gZ2V0IG91dCBvZiB5b3VyIGNvbWZvcnQgem9uZXMgLSB0aGUgaG91c2UgYW5kIHRoZSBjaXR5IHlvdSBrbm93IHRvbyB3ZWxsLiBTbyBkbyB0aGF0IG1vcmUsIEkgdGhpbmsgdGhhdCB3aWxsIGV2ZW50dWFsbHkgZm9ybSBhIGhhYml0IG9mIGdldHRpbmcgb3V0IG9mIHlvdXIgY29tZm9ydCB6b25lcyBzb21laG93LlxuXG5Zb3UndmUgbWFkZSBmcmllbmRzIGZhc3RlciB0aGFuIG1lIGFuZCB3aGF0IEkgdGhvdWdodC5JIGhhdmUgb2JzZXJ2ZWQgeW91IGdyb3cgYW5kIGFkYXB0IHZlcnkgd2VsbCB0byBBdXNzaWUgYW5kIEkgaGF2ZSBubyBkb3VidCB0aGF0IHlvdXIgcGVyc29uYWxpdHkgYW5kIHlvdXIgaW50ZWxsaWdlbmNlIHdpbGwgdGFrZSB5b3UgZmFyIGluIEF1c3NpZS4gQWltIGhpZ2ggYW5kLCB3aGF0ZXZlciBmcmllbmRzIGFuZCBjb21wYW5pZXMgeW91IGFyZSBpbiwgbWFrZSBzdXJlIHRoZXkgYXJlIGEgZ29vZCBmaXQgZm9yIHlvdSAoSSBzYXkgdGhpcyBiZWNhdXNlIEkgaGF2ZSBiZWVuIGluIG1lZGlvY3JlIGNvbXBhbmllcyBhbmQgeW91IGRvbid0IGJlbG9uZyB0byB0aG9zZSkuXG5cbkJlIGh1bmdyeSwgYnJvdGhlci4iLCJzaWduYXR1cmUiOiJCZXN0IiwiaW1hZ2VzIjpbImhhMS5qcGciLCJoYTIuanBnIl19LCJtb20iOnsicmVjZWl2ZXJJZCI6Im1vbSIsInJlY2VpdmVyRGlzcGxheU5hbWUiOiJNb20iLCJjb3ZlclRpdGxlIjoiSGFwcHkgTmV3IFllYXIhIiwiY292ZXJTdWJ0aXRsZSI6InRvIG15IG1vbSIsImluc2lkZVRpdGxlIjoiIiwiaW5zaWRlQm9keSI6IkRlYXIgTW9tLFxuXG5JIHdpc2ggeW91IGFub3RoZXIgeWVhciBmdWxsIG9mIGhlYWx0aCBhbmQgaGFwcGluZXNzIHdpdGggeW91ciBmYW1pbHkuXG5cbkkgd2FudCB0byB0YWtlIHRoaXMgb3Bwb3J0dW5pdHkgdG8gdGhhbmsgeW91IGZvciB5b3VyIHN1cHBvcnQgd2l0aCBPREkgYW5kIGEgbG90IG1vcmUgYXQgd29yay4gSGVyZSB0byBhbm90aGVyIGF3ZXNvbWUgeWVhciB3b3JraW5nIHRvZ2V0aGVyIPCfpJzwn6SbISIsInNpZ25hdHVyZSI6IkJlc3QifSwiZGFkIjp7InJlY2VpdmVySWQiOiJkYWQiLCJyZWNlaXZlckRpc3BsYXlOYW1lIjoiRGFkIiwiY292ZXJUaXRsZSI6IkhhcHB5IE5ldyBZZWFyISIsImNvdmVyU3VidGl0bGUiOiJ0byBteSBkYWQiLCJpbnNpZGVUaXRsZSI6IiIsImluc2lkZUJvZHkiOiJEZWFyIERhZCxcblxuSSB3aXNoIHlvdSBhbm90aGVyIHllYXIgZnVsbCBvZiBoZWFsdGggYW5kIGhhcHBpbmVzcyB3aXRoIHlvdXIgZmFtaWx5LlxuXG5JIHdhbnQgdG8gdGFrZSB0aGlzIG9wcG9ydHVuaXR5IHRvIHRoYW5rIHlvdSBmb3IgeW91ciBzdXBwb3J0IHdpdGggT0RJIGFuZCBhIGxvdCBtb3JlIGF0IHdvcmsuIEhlcmUgdG8gYW5vdGhlciBhd2Vzb21lIHllYXIgd29ya2luZyB0b2dldGhlciDwn6Sc8J+kmyEiLCJzaWduYXR1cmUiOiJCZXN0In0sInJvbGFuZCI6eyJyZWNlaXZlcklkIjoicm9sYW5kIiwicmVjZWl2ZXJEaXNwbGF5TmFtZSI6Ik1pbmgiLCJjb3ZlclRpdGxlIjoiSGFwcHkgTmV3IFllYXIhIiwiY292ZXJTdWJ0aXRsZSI6InRvIG15IGZpcnN0IEJyaXNzaWUgZnJpZW5kIiwiaW5zaWRlVGl0bGUiOiIiLCJpbnNpZGVCb2R5IjoiRGVhciBNaW5oLFxuXG5JIHdpc2ggeW91IGFub3RoZXIgeWVhciBmdWxsIG9mIGhlYWx0aCBhbmQgaGFwcGluZXNzIHdpdGggeW91ciBmYW1pbHkuXG5cbkkgd2FudCB0byB0YWtlIHRoaXMgb3Bwb3J0dW5pdHkgdG8gdGhhbmsgeW91IGZvciB5b3VyIHN1cHBvcnQgd2l0aCBPREkgYW5kIGEgbG90IG1vcmUgYXQgd29yay4gSGVyZSB0byBhbm90aGVyIGF3ZXNvbWUgeWVhciB3b3JraW5nIHRvZ2V0aGVyIPCfpJzwn6SbISIsInNpZ25hdHVyZSI6IkJlc3QifSwibWluaGRhbmciOnsicmVjZWl2ZXJJZCI6Im1pbmhkYW5nIiwicmVjZWl2ZXJEaXNwbGF5TmFtZSI6IkRhbmciLCJjb3ZlclRpdGxlIjoiSGFwcHkgTmV3IFllYXIhIiwiY292ZXJTdWJ0aXRsZSI6InRvIG15IGZpcnN0IEJyaXNzaWUgZnJpZW5kIiwiaW5zaWRlVGl0bGUiOiIiLCJpbnNpZGVCb2R5IjoiRGVhciBEYW5nLFxuXG5JIHdpc2ggeW91IGFub3RoZXIgeWVhciBmdWxsIG9mIGhlYWx0aCBhbmQgaGFwcGluZXNzIHdpdGggeW91ciBmYW1pbHkuXG5cbkkgd2FudCB0byB0YWtlIHRoaXMgb3Bwb3J0dW5pdHkgdG8gdGhhbmsgeW91IGZvciB5b3VyIHN1cHBvcnQgd2l0aCBPREkgYW5kIGEgbG90IG1vcmUgYXQgd29yay4gSGVyZSB0byBhbm90aGVyIGF3ZXNvbWUgeWVhciB3b3JraW5nIHRvZ2V0aGVyIPCfpJzwn6SbISIsInNpZ25hdHVyZSI6IkJlc3QifSwiZ293cmkiOnsicmVjZWl2ZXJJZCI6Imdvd3JpIiwicmVjZWl2ZXJEaXNwbGF5TmFtZSI6Ikdvd3JpIiwiY292ZXJUaXRsZSI6IkhhcHB5IE5ldyBZZWFyISIsImNvdmVyU3VidGl0bGUiOiJBIHNtYWxsIGNhcmQganVzdCBmb3IgeW91IiwiaW5zaWRlVGl0bGUiOiIiLCJpbnNpZGVCb2R5IjoiRGVhciBHb3dyaSxcblxuSGFwcHkgTmV3IFllYXIhXG5cbiIsInNpZ25hdHVyZSI6IkJlc3QifSwiYm9uZ2dvbiI6eyJyZWNlaXZlcklkIjoiYm9uZ2dvbiIsInJlY2VpdmVyRGlzcGxheU5hbWUiOiJib25nZ29uIiwiY292ZXJUaXRsZSI6IkhhcHB5IE5ldyBZZWFyISIsImNvdmVyU3VidGl0bGUiOiJBIHNtYWxsIGNhcmQganVzdCBmb3IgeW91IiwiaW5zaWRlVGl0bGUiOiIiLCJpbnNpZGVCb2R5IjoiRGVhciBOaGksXG5cbkkgd2lzaCB5b3UgYW5vdGhlciB5ZWFyIGZ1bGwgb2YgaGVhbHRoIGFuZCBoYXBwaW5lc3Mgd2l0aCB5b3VyIGZhbWlseS5cblxuSSB3YW50IHRvIHRha2UgdGhpcyBvcHBvcnR1bml0eSB0byB0aGFuayB5b3UgZm9yIHlvdXIgc3VwcG9ydCB3aXRoIE9ESSBhbmQgYSBsb3QgbW9yZSBhdCB3b3JrLiBIZXJlIHRvIGFub3RoZXIgYXdlc29tZSB5ZWFyIHdvcmtpbmcgdG9nZXRoZXIg8J+knPCfpJshIiwic2lnbmF0dXJlIjoiQmVzdCJ9LCJiYTQ0eSI6eyJyZWNlaXZlcklkIjoiYmE0NHkiLCJyZWNlaXZlckRpc3BsYXlOYW1lIjoiYmE0NHkiLCJjb3ZlclRpdGxlIjoiSGFwcHkgTmV3IFllYXIhIiwiY292ZXJTdWJ0aXRsZSI6Ik9wZW4gbWUiLCJpbnNpZGVUaXRsZSI6IkNoZWVycyIsImluc2lkZUJvZHkiOiJEZWFyIGJhNDR5LFxuXG5UT0RPOiBXcml0ZSB5b3VyIHBlcnNvbmFsIG1lc3NhZ2UgaGVyZS5cblxuVGhhbmtzIGZvciBiZWluZyBwYXJ0IG9mIG15IHllYXIg4oCUIGxldCdzIG1ha2UgdGhlIG5leHQgb25lIGV2ZW4gYmV0dGVyLlxuXG5UT0RPOiBBZGQgYSBzaG9ydCB3aXNoIHRoYXQgZml0cyB5b3VyIGZyaWVuZHNoaXAuXG5cbk1vcmUgbGF1Z2h0ZXIsIG1vcmUgZ3Jvd3RoLCBhbmQgbW9yZSBnb29kIG1vbWVudHMuIiwic2lnbmF0dXJlIjoi4oCUIFJvZG8ifSwib3B1c21heGltdXMiOnsicmVjZWl2ZXJJZCI6Im9wdXNtYXhpbXVzIiwicmVjZWl2ZXJEaXNwbGF5TmFtZSI6Im9wdXNtYXhpbXVzIiwiY292ZXJUaXRsZSI6IkhhcHB5IE5ldyBZZWFyISIsImNvdmVyU3VidGl0bGUiOiJGcm9tIG1lIHRvIHlvdSIsImluc2lkZVRpdGxlIjoiTGV0J3MgZ28iLCJpbnNpZGVCb2R5IjoiRGVhciBvcHVzbWF4aW11cyxcblxuV2lzaGluZyB5b3UgbW9tZW50dW0sIGNsYXJpdHksIGFuZCBhIHllYXIgdGhhdCBmZWVscyBsaWtlIGEgYmlnIHN0ZXAgZm9yd2FyZC5cblxuTWF5IDIwMjYgYnJpbmcgeW91IGJvbGQgaWRlYXMgYW5kIGNhbG0gZXhlY3V0aW9uLiIsInNpZ25hdHVyZSI6IuKAlCBSb2RvIn0sIlN0ZXZlIjp7InJlY2VpdmVySWQiOiJTdGV2ZSIsInJlY2VpdmVyRGlzcGxheU5hbWUiOiJTdGV2ZSIsImNvdmVyVGl0bGUiOiJIYXBweSBOZXcgWWVhciEiLCJjb3ZlclN1YnRpdGxlIjoiQSBzbWFsbCBjYXJkIGp1c3QgZm9yIHlvdSIsImluc2lkZVRpdGxlIjoiIiwiaW5zaWRlQm9keSI6IkRlYXIgU3RldmUsXG5cbkkgd2lzaCB5b3UgYW5vdGhlciB5ZWFyIGZ1bGwgb2YgaGVhbHRoIGFuZCBoYXBwaW5lc3Mgd2l0aCB5b3VyIGZhbWlseS5cblxuSSB3YW50IHRvIHRha2UgdGhpcyBvcHBvcnR1bml0eSB0byB0aGFuayB5b3UgZm9yIHlvdXIgc3VwcG9ydCB3aXRoIE9ESSBhbmQgYSBsb3QgbW9yZSBhdCB3b3JrLiBIZXJlIHRvIGFub3RoZXIgYXdlc29tZSB5ZWFyIHdvcmtpbmcgdG9nZXRoZXIg8J+knPCfpJshIiwic2lnbmF0dXJlIjoiQmVzdCJ9fQ=='

// Decode and parse the content
const decodeContent = (): Record<string, HpnyCardContent> => {
	try {
		const base64Decoded = atob(ENCODED_CONTENT)
		// Convert binary string to Uint8Array for proper UTF-8 decoding
		const bytes = new Uint8Array(base64Decoded.length)
		for (let i = 0; i < base64Decoded.length; i++) {
			bytes[i] = base64Decoded.charCodeAt(i)
		}
		// Decode UTF-8 properly to handle emojis
		const decoded = new TextDecoder('utf-8').decode(bytes)
		// Validate the decoded string doesn't contain unescaped control characters
		const parsed = JSON.parse(decoded) as Record<string, HpnyCardContent>
		return parsed
	} catch (error) {
		console.error('Failed to decode HPNY_CONTENT:', error)
		if (error instanceof SyntaxError) {
			console.error('This is likely due to unescaped control characters in the JSON.')
			console.error('Please regenerate the encoded content using: node encode-content.cjs')
		}
		return {}
	}
}

const HPNY_CONTENT = decodeContent()

const isHpnyReceiver = (value: string): value is string => {
	return Object.prototype.hasOwnProperty.call(HPNY_CONTENT, value)
}

const Hpny = () => {
	const { name } = useParams<{ name: string }>()
	const [isMobile, setIsMobile] = useState<boolean>(false)

	const receiverKey = name ?? ''

	if (!isHpnyReceiver(receiverKey)) {
		return <Navigate to="/" replace />
	}

	const content = useMemo(() => HPNY_CONTENT[receiverKey], [receiverKey])

	useEffect(() => {
		document.title = `Happy New Year, ${content.receiverDisplayName}`
	}, [content.receiverDisplayName])

	useEffect(() => {
		const checkMobile = () => {
			setIsMobile(window.innerWidth < 640)
		}

		checkMobile()
		window.addEventListener('resize', checkMobile)
		return () => window.removeEventListener('resize', checkMobile)
	}, [])

	return (
		<div className="fixed inset-0 z-50 bg-gradient-to-br from-slate-950 via-slate-900 to-black text-white">
			<div className="h-full w-full flex items-center justify-center p-6">
				<div className="w-full max-w-4xl flex flex-col items-center gap-6">
					{isMobile ? <HpnyCardMobile content={content} /> : <HpnyCard content={content} />}

					<p className="text-xs text-white/60 text-center max-w-md">just tap, tap, tap...</p>
				</div>
			</div>
		</div>
	)
}

export default Hpny
