import { Navigate, useParams } from 'react-router-dom'
import { useEffect, useMemo, useState } from 'react'
import HpnyCard from '../../components/HpnyCard/HpnyCard'
import HpnyCardMobile from '../../components/HpnyCard/HpnyCardMobile'
import type { HpnyCardContent } from './hpnyContent'

// Encoded HPNY_CONTENT (base64)
const ENCODED_CONTENT =
	'eyI0aG00ZCI6eyJyZWNlaXZlcklkIjoiNGhtNGQiLCJyZWNlaXZlckRpc3BsYXlOYW1lIjoiQWhtYWQiLCJjb3ZlclRpdGxlIjoiSGFwcHkgTmV3IFllYXIhIiwiY292ZXJTdWJ0aXRsZSI6IkEgc21hbGwgY2FyZCBqdXN0IGZvciB5b3UiLCJpbnNpZGVUaXRsZSI6IiIsImluc2lkZUJvZHkiOiJEZWFyIEFobWFkLFxuXG5JIHdpc2ggeW91IGFub3RoZXIgeWVhciBmdWxsIG9mIGhlYWx0aCBhbmQgaGFwcGluZXNzIHdpdGggeW91ciBmYW1pbHkuXG5cbkkgd2FudCB0byB0YWtlIHRoaXMgb3Bwb3J0dW5pdHkgdG8gdGhhbmsgeW91IGZvciB5b3VyIHN1cHBvcnQgd2l0aCBPREkgYW5kIGEgbG90IG1vcmUgYXQgd29yay4gSGVyZSB0byBhbm90aGVyIGF3ZXNvbWUgeWVhciB3b3JraW5nIHRvZ2V0aGVyIPCfpJzwn6SbISIsInNpZ25hdHVyZSI6IkJlc3QifSwiRGlrNWhhIjp7InJlY2VpdmVySWQiOiJEaWtzaGEiLCJyZWNlaXZlckRpc3BsYXlOYW1lIjoiRGlrc2hhIiwiY292ZXJUaXRsZSI6IkhhcHB5IE5ldyBZZWFyISIsImNvdmVyU3VidGl0bGUiOiJBIHNtYWxsIGNhcmQganVzdCBmb3IgeW91IiwiaW5zaWRlVGl0bGUiOiIiLCJpbnNpZGVCb2R5IjoiRGVhciBEaWtzaGEsXG5cbkkgd2lzaCB5b3UgYW5vdGhlciB5ZWFyIGZ1bGwgb2YgaGVhbHRoIGFuZCBoYXBwaW5lc3Mgd2l0aCB5b3VyIGh1YmJ5IGFuZCBmYW1pbHkuXG5cblRoYW5rIHlvdSBmb3IgeW91ciBmb3IgaGVscGluZyBtZSBwZXJzb25hbGx5IGFuZCB0aGUgdGVhbSBvbiBtdWx0aXBsZSBmcm9udHMuIEZyb20ganVzdCBzaG9ydCAzIG1vbnRocywgSSd2ZSBzZWVuIHlvdSBicmluZyBhIHRvbiBvZiB2YWx1ZXMgdG8gdGhlIHRlYW0gYW5kIEkgYWRtaXJlIHRoYXQuIEhlcmUgdG8gYW5vdGhlciBhd2Vzb21lIHllYXIgd29ya2luZyB0b2dldGhlciDwn6Sc8J+kmyEiLCJzaWduYXR1cmUiOiJCZXN0In0sIkFsdjFuIjp7InJlY2VpdmVySWQiOiJBbHYxbiIsInJlY2VpdmVyRGlzcGxheU5hbWUiOiJBbHZpbiIsImNvdmVyVGl0bGUiOiJIYXBweSBOZXcgWWVhciEiLCJjb3ZlclN1YnRpdGxlIjoiQSBzbWFsbCBjYXJkIGp1c3QgZm9yIHlvdSIsImluc2lkZVRpdGxlIjoiIiwiaW5zaWRlQm9keSI6IkRlYXIgQWx2aW4sXG5cbkkgd2lzaCB5b3UgYW5vdGhlciB5ZWFyIGZ1bGwgb2YgaGVhbHRoIGFuZCBoYXBwaW5lc3Mgd2l0aCB5b3VyIGZhbWlseS5cblxuSSB3YW50IHRvIHRha2UgdGhpcyBvcHBvcnR1bml0eSB0byB0aGFuayB5b3UgZm9yIHRydXN0aW5nIG1lLCBsZXR0aW5nIG1lIGJlIGEgcGFydCBvZiB0aGlzIGFtYXppbmcgdGVhbSBhbmQgdHJlbWVuZG91cyBzdXBwb3J0IHlvdSd2ZSBiZWVuIHByb3ZpZGluZy4gSGVyZSB0byBhbm90aGVyIGF3ZXNvbWUgeWVhciB3b3JraW5nIHRvZ2V0aGVyIFxu8J+knPCfpJshIiwic2lnbmF0dXJlIjoiQmVzdCJ9LCJqZXNzaWUyNiI6eyJyZWNlaXZlcklkIjoiamVzc2llMjYiLCJyZWNlaXZlckRpc3BsYXlOYW1lIjoiSmVzc2llIiwiY292ZXJUaXRsZSI6IkhhcHB5IE5ldyBZZWFyISIsImNvdmVyU3VidGl0bGUiOiJBIHNtYWxsIGNhcmQganVzdCBmb3IgeW91IiwiaW5zaWRlVGl0bGUiOiIiLCJpbnNpZGVCb2R5IjoiRGVhciBKZXNzaWUsXG5cbkkgd2lzaCB5b3UgYW5vdGhlciB5ZWFyIGZ1bGwgb2YgaGVhbHRoIGFuZCBoYXBwaW5lc3Mgd2l0aCB5b3VyIGJpZyBmYW1pbHkuXG5cbkkgd2FudCB0byB0YWtlIHRoaXMgb3Bwb3J0dW5pdHkgdG8gdGhhbmsgeW91IGZvciB5b3VyIGxlYWRlcnNoaXAsIGZvciB0cnVzdGluZyBtZSBhbmQgbGV0dGluZyBtZSBiZSBhIHBhcnQgb2YgdGhlIHRlYW0uXG5cbkhlcmUgdG8gYSBuZXcgZnJ1aXRmdWwgeWVhciEiLCJzaWduYXR1cmUiOiJCZXN0In0sIjRudGhvbnkiOnsicmVjZWl2ZXJJZCI6IjRudGhvbnkiLCJyZWNlaXZlckRpc3BsYXlOYW1lIjoiQW50aG9ueSIsImNvdmVyVGl0bGUiOiJIYXBweSBOZXcgWWVhciEiLCJjb3ZlclN1YnRpdGxlIjoiQSBzbWFsbCBjYXJkIGp1c3QgZm9yIHlvdSIsImluc2lkZVRpdGxlIjoiIiwiaW5zaWRlQm9keSI6IkRlYXIgQW50aG9ueSxcblxuSSB3aXNoIHlvdSBhbmQgeW91ciBmYW1pbHkgYW5vdGhlciB5ZWFyIGZ1bGwgb2YgaGVhbHRoIGFuZCBoYXBwaW5lc3MuIEFuZCBJIHdpc2ggZXZlcnl0aGluZyB3b3VsZCBnbyB3ZWxsIHdpdGggeW91ciBkYXVnaHRlcidzIHRyZWF0bWVudCwgcGxlYXNlIGxldCBtZSBrbm93IGlmIEkgY2FuIGhlbHAgeW91IGluIGFueSB3YXksIEkgZG8ga25vdyBWaWV0bmFtIGFsc28gaGFzIHZlcnkgaWYgbm90IG1vcmUgY2FwYWJsZSBkb2N0b3JzLlxuXG5BbmQsIHRoYW5rIHlvdSBmb3IgbGVhZGVyc2hpcCwgZm9yIHRydXN0aW5nIG1lIGFuZCBsZXR0aW5nIG1lIGJlIGEgcGFydCBvZiB0aGUgdGVhbS4iLCJzaWduYXR1cmUiOiJCZXN0In0sImx1Y2l1c0NhcCI6eyJyZWNlaXZlcklkIjoibHVjaXVzQ2FwIiwicmVjZWl2ZXJEaXNwbGF5TmFtZSI6IlZpbmgiLCJjb3ZlclRpdGxlIjoiSGFwcHkgTmV3IFllYXIhIiwiY292ZXJTdWJ0aXRsZSI6IlRvIGdyZWF0bmVzcyBhbmQgcHJvc3Blcml0eSIsImluc2lkZVRpdGxlIjoiIiwiaW5zaWRlQm9keSI6IkRlYXIgVmluaCxcblxuSSB3aXNoIHlvdSBhbmQgTHVjaXVzIENhcGl0YWwgYW5vdGhlciBwcm9zcGVyb3VzIHllYXIgd2l0aCBncmVhdGVyIGFjaGlldmVtZW50cyBhbmQgc3VjY2Vzc2VzLiBKdXN0IGFzIGltcG9ydGFudGx5LCB0YWtlIGdvb2QgY2FyZSBvZiB5b3VyIGhlYWx0aCBhbmQgZXhlcmNpc2UgbW9yZSBzaXIuXG5cbkFuZCB0aGFuayB5b3UgZm9yIHRoZSBmcmllbmRzaGlwLCBwYXJ0bmVyc2hpcCBhbmQgd2hhdGV2ZXIgZWxzZSB0aGVyZSBpcyEiLCJzaWduYXR1cmUiOiJCZXN0In0sIm5pbmEiOnsicmVjZWl2ZXJJZCI6Im5pbmEiLCJyZWNlaXZlckRpc3BsYXlOYW1lIjoiTmluYSIsImNvdmVyVGl0bGUiOiJIYXBweSBOZXcgWWVhciEiLCJjb3ZlclN1YnRpdGxlIjoiQSBzbWFsbCBjYXJkIGp1c3QgZm9yIHlvdSIsImluc2lkZVRpdGxlIjoiIiwiaW5zaWRlQm9keSI6IkRlYXIgTmluYSxcblxuSGFwcHkgbmV3IHllYXIgYW5kIGhhcHB5IDEgeWVhciBhcm91bmQgdGhlIHN1biB3aXRoIHlvdSFcblxuVGhpcyB5ZWFyLCB3ZSBib3RoIHdpbGwgbmVlZCB0byBjaGFuZ2UgZm9yIHRoZSBiZXR0ZXIuIEkgd2lsbCBtYWtlIGEgcHJvbWlzZSB0byB5b3UgdGhhdCB3ZSB3aWxsIHNwZW5kIG1vcmUgcXVhbGl0eSB0aW1lIHRvZ2V0aGVyLCBuaWdodC10aW1lIHdpdGhvdXQgc29jaWFsIG1lZGlhIGRpc3J1cHRpb24sIGdyb3cgc21hcnRlciBlbW90aW9uYWxseSBhbmQgaW50ZWxsaWdlbnRseSwgd2VhciBjb29sLWFzcyBvdXRmaXRzIGFuZCBnbyBvbiBhIGRhdGUtbmlnaHQgZXZlcnkgbW9udGguIFRoYXQncyB0aGUgbGVhc3QgSSBjYW4gZG8uXG5cbkkgb25seSB3aXNoIHRoYXQgdGhpcyB5ZWFyLCB5b3Ugd2lsbCBoYXZlIG1vcmUgYXVkYWNpdHkgdG8gc3BlYWsgd2hhdCB5b3UgdGhpbmssIGRvIHdoYXQgeW91IHdhbnQsIGdldCB3aGF0IHlvdSBob3BlIGZvciBhbmQgdGFrZSBhY3Rpb24gdG8gYWNoaWV2ZSB5b3VyIGdvYWxzLiBNb3N0IGltcG9ydGFudGx5LCB0aGluayBhYm91dCB3aGF0IHlvdSB3YW50IGluIGxpZmUgb3IgdGhpcyB5ZWFyLCB5b3UncmUgeW91bmcgc28gY2hlcmlzaCBldmVyeSBwaWVjZSBvZiB0aW1lIHlvdSBoYXZlIGFuZCBtYWtlIHRoZSBtb3N0IG9mIGl0LiBJJ20gYSBndXkgc28gSSdtIHNvIGxvZ2ljYWwgYWJvdXQgdGhlc2Ugc3R1ZmZzLCBJIHBsYW4gYW5kIGNhbGN1bGF0ZSBhIGxvdCwgbWF5YmUgYSBiaXQgb2YgdGhhdCAobG9naWNhbCwgcGxhbm5pbmcsIGNhbGN1bGF0aW5nKSB3aWxsIGRvIGdvb2QgZm9yIHlvdXIgbGlmZS4gU28sIGFuc3dlciB0aGlzOiBXaGF0IGRvIHlvdSB3YW50IGZvciB5b3Vyc2VsZiB0aGlzIHllYXI/XG5cblRoYW5rIHlvdSBmb3IgYnJpbmcgc21pbGVzIHRvIG15IGZhY2UgYWxsIHRoZSB0aW1lLiIsInNpZ25hdHVyZSI6IkxvdmUgeW91IDwzIn0sImFsNG4iOnsicmVjZWl2ZXJJZCI6ImFsNG4iLCJyZWNlaXZlckRpc3BsYXlOYW1lIjoiQWxhbiIsImNvdmVyVGl0bGUiOiJIYXBweSBOZXcgWWVhciEiLCJjb3ZlclN1YnRpdGxlIjoidG8gbXkgYnJvdGhlciIsImluc2lkZVRpdGxlIjoiIiwiaW5zaWRlQm9keSI6IkRlYXIgSG9hbmcgQW5oLFxuXG5IYXBweSBuZXcgeWVhciBhbmQgd2VsY29tZSB5b3UgdG8gdGhlIGFnZSBvZiBpbmRlcGVuZGVuY2UgKDE4eW8pIVxuXG5Zb3UgYXJlIGVhcm5pbmcgeW91ciBvd24gbW9uZXkgbm93LCBJJ20gc28gaGFwcHkhIExpZmUgaXMgc3RpbGwgbG9uZyBidXQgbWFrZSBzdXJlIHlvdSB1c2UgaXQgd2lzZWx5LCBtYWtlIHBsYW5zIHRvIHRyYXZlbCBhcm91bmQgbW9yZSAoYXQgbGVhc3QgMSBuZWFyIGFuZCAxIGZhciBwbGFjZSBhIHllYXIpIGFzIHRoaXMgaXMgd2hhdCBJIHdpc2ggSSBoYXZlIGRvbmUgaW4geW91ciBhZ2UuIEkgdGhvdWdodCB3aGVuIEkgaGF2ZSBtb25leSwgSSB3aWxsIHRyYXZlbCBtb3JlIGJ1dCBJIGNhbiBoYXJkbHkgZmluZCB0aGUgdGltZS5cblxuVHJhdmVsaW5nIGlzIG9uZSBvZiB0aGUgY2hlYXAgYWN0aW9ucyB0aGF0IHlvdSBjYW4gZG8gdG8gZ2V0IG91dCBvZiB5b3VyIGNvbWZvcnQgem9uZXMgLSB0aGUgaG91c2UgYW5kIHRoZSBjaXR5IHlvdSBrbm93IHRvbyB3ZWxsLiBTbyBkbyB0aGF0IG1vcmUsIEkgdGhpbmsgdGhhdCB3aWxsIGV2ZW50dWFsbHkgZm9ybSBhIGhhYml0IG9mIGdldHRpbmcgb3V0IG9mIHlvdXIgY29tZm9ydCB6b25lcyBzb21laG93LlxuXG5CZSBodW5ncnksIGJyb3RoZXIuIiwic2lnbmF0dXJlIjoiQmVzdCJ9LCJyb2xhbmQiOnsicmVjZWl2ZXJJZCI6InJvbGFuZCIsInJlY2VpdmVyRGlzcGxheU5hbWUiOiJNaW5oIiwiY292ZXJUaXRsZSI6IkhhcHB5IE5ldyBZZWFyISIsImNvdmVyU3VidGl0bGUiOiJ0byBteSBmaXJzdCBCcmlzc2llIGZyaWVuZCIsImluc2lkZVRpdGxlIjoiIiwiaW5zaWRlQm9keSI6IkRlYXIgTWluaCxcblxuSSB3aXNoIHlvdSBhbm90aGVyIHllYXIgZnVsbCBvZiBoZWFsdGggYW5kIGhhcHBpbmVzcyB3aXRoIHlvdXIgZmFtaWx5LlxuXG5JIHdhbnQgdG8gdGFrZSB0aGlzIG9wcG9ydHVuaXR5IHRvIHRoYW5rIHlvdSBmb3IgeW91ciBzdXBwb3J0IHdpdGggT0RJIGFuZCBhIGxvdCBtb3JlIGF0IHdvcmsuIEhlcmUgdG8gYW5vdGhlciBhd2Vzb21lIHllYXIgd29ya2luZyB0b2dldGhlciDwn6Sc8J+kmyEiLCJzaWduYXR1cmUiOiJCZXN0In0sIm1pbmhkYW5nIjp7InJlY2VpdmVySWQiOiJtaW5oZGFuZyIsInJlY2VpdmVyRGlzcGxheU5hbWUiOiJEYW5nIiwiY292ZXJUaXRsZSI6IkhhcHB5IE5ldyBZZWFyISIsImNvdmVyU3VidGl0bGUiOiJ0byBteSBmaXJzdCBCcmlzc2llIGZyaWVuZCIsImluc2lkZVRpdGxlIjoiIiwiaW5zaWRlQm9keSI6IkRlYXIgRGFuZyxcblxuSSB3aXNoIHlvdSBhbm90aGVyIHllYXIgZnVsbCBvZiBoZWFsdGggYW5kIGhhcHBpbmVzcyB3aXRoIHlvdXIgZmFtaWx5LlxuXG5JIHdhbnQgdG8gdGFrZSB0aGlzIG9wcG9ydHVuaXR5IHRvIHRoYW5rIHlvdSBmb3IgeW91ciBzdXBwb3J0IHdpdGggT0RJIGFuZCBhIGxvdCBtb3JlIGF0IHdvcmsuIEhlcmUgdG8gYW5vdGhlciBhd2Vzb21lIHllYXIgd29ya2luZyB0b2dldGhlciDwn6Sc8J+kmyEiLCJzaWduYXR1cmUiOiJCZXN0In0sImdvd3JpIjp7InJlY2VpdmVySWQiOiJnb3dyaSIsInJlY2VpdmVyRGlzcGxheU5hbWUiOiJHb3dyaSIsImNvdmVyVGl0bGUiOiJIYXBweSBOZXcgWWVhciEiLCJjb3ZlclN1YnRpdGxlIjoiQSBzbWFsbCBjYXJkIGp1c3QgZm9yIHlvdSIsImluc2lkZVRpdGxlIjoiIiwiaW5zaWRlQm9keSI6IkRlYXIgR293cmksXG5cbkhhcHB5IE5ldyBZZWFyIVxuXG4iLCJzaWduYXR1cmUiOiJCZXN0In0sImJvbmdnb24iOnsicmVjZWl2ZXJJZCI6ImJvbmdnb24iLCJyZWNlaXZlckRpc3BsYXlOYW1lIjoiYm9uZ2dvbiIsImNvdmVyVGl0bGUiOiJIYXBweSBOZXcgWWVhciEiLCJjb3ZlclN1YnRpdGxlIjoiQSBzbWFsbCBjYXJkIGp1c3QgZm9yIHlvdSIsImluc2lkZVRpdGxlIjoiIiwiaW5zaWRlQm9keSI6IkRlYXIgTmhpLFxuXG5JIHdpc2ggeW91IGFub3RoZXIgeWVhciBmdWxsIG9mIGhlYWx0aCBhbmQgaGFwcGluZXNzIHdpdGggeW91ciBmYW1pbHkuXG5cbkkgd2FudCB0byB0YWtlIHRoaXMgb3Bwb3J0dW5pdHkgdG8gdGhhbmsgeW91IGZvciB5b3VyIHN1cHBvcnQgd2l0aCBPREkgYW5kIGEgbG90IG1vcmUgYXQgd29yay4gSGVyZSB0byBhbm90aGVyIGF3ZXNvbWUgeWVhciB3b3JraW5nIHRvZ2V0aGVyIPCfpJzwn6SbISIsInNpZ25hdHVyZSI6IkJlc3QifSwiYmE0NHkiOnsicmVjZWl2ZXJJZCI6ImJhNDR5IiwicmVjZWl2ZXJEaXNwbGF5TmFtZSI6ImJhNDR5IiwiY292ZXJUaXRsZSI6IkhhcHB5IE5ldyBZZWFyISIsImNvdmVyU3VidGl0bGUiOiJPcGVuIG1lIiwiaW5zaWRlVGl0bGUiOiJDaGVlcnMiLCJpbnNpZGVCb2R5IjoiRGVhciBiYTQ0eSxcblxuVE9ETzogV3JpdGUgeW91ciBwZXJzb25hbCBtZXNzYWdlIGhlcmUuXG5cblRoYW5rcyBmb3IgYmVpbmcgcGFydCBvZiBteSB5ZWFyIOKAlCBsZXQncyBtYWtlIHRoZSBuZXh0IG9uZSBldmVuIGJldHRlci5cblxuVE9ETzogQWRkIGEgc2hvcnQgd2lzaCB0aGF0IGZpdHMgeW91ciBmcmllbmRzaGlwLlxuXG5Nb3JlIGxhdWdodGVyLCBtb3JlIGdyb3d0aCwgYW5kIG1vcmUgZ29vZCBtb21lbnRzLiIsInNpZ25hdHVyZSI6IuKAlCBSb2RvIn0sIm9wdXNtYXhpbXVzIjp7InJlY2VpdmVySWQiOiJvcHVzbWF4aW11cyIsInJlY2VpdmVyRGlzcGxheU5hbWUiOiJvcHVzbWF4aW11cyIsImNvdmVyVGl0bGUiOiJIYXBweSBOZXcgWWVhciEiLCJjb3ZlclN1YnRpdGxlIjoiRnJvbSBtZSB0byB5b3UiLCJpbnNpZGVUaXRsZSI6IkxldCdzIGdvIiwiaW5zaWRlQm9keSI6IkRlYXIgb3B1c21heGltdXMsXG5cbldpc2hpbmcgeW91IG1vbWVudHVtLCBjbGFyaXR5LCBhbmQgYSB5ZWFyIHRoYXQgZmVlbHMgbGlrZSBhIGJpZyBzdGVwIGZvcndhcmQuXG5cbk1heSAyMDI2IGJyaW5nIHlvdSBib2xkIGlkZWFzIGFuZCBjYWxtIGV4ZWN1dGlvbi4iLCJzaWduYXR1cmUiOiLigJQgUm9kbyJ9LCJTdGV2ZSI6eyJyZWNlaXZlcklkIjoiU3RldmUiLCJyZWNlaXZlckRpc3BsYXlOYW1lIjoiU3RldmUiLCJjb3ZlclRpdGxlIjoiSGFwcHkgTmV3IFllYXIhIiwiY292ZXJTdWJ0aXRsZSI6IkEgc21hbGwgY2FyZCBqdXN0IGZvciB5b3UiLCJpbnNpZGVUaXRsZSI6IiIsImluc2lkZUJvZHkiOiJEZWFyIFN0ZXZlLFxuXG5JIHdpc2ggeW91IGFub3RoZXIgeWVhciBmdWxsIG9mIGhlYWx0aCBhbmQgaGFwcGluZXNzIHdpdGggeW91ciBmYW1pbHkuXG5cbkkgd2FudCB0byB0YWtlIHRoaXMgb3Bwb3J0dW5pdHkgdG8gdGhhbmsgeW91IGZvciB5b3VyIHN1cHBvcnQgd2l0aCBPREkgYW5kIGEgbG90IG1vcmUgYXQgd29yay4gSGVyZSB0byBhbm90aGVyIGF3ZXNvbWUgeWVhciB3b3JraW5nIHRvZ2V0aGVyIPCfpJzwn6SbISIsInNpZ25hdHVyZSI6IkJlc3QifX0='

// Decode and parse the content
const decodeContent = (): Record<string, HpnyCardContent> => {
	try {
		const decoded = atob(ENCODED_CONTENT)
		return JSON.parse(decoded) as Record<string, HpnyCardContent>
	} catch (error) {
		console.error('Failed to decode HPNY_CONTENT:', error)
		return {}
	}
}

const HPNY_CONTENT = decodeContent()

const isHpnyReceiver = (value: string): value is string => {
	return Object.prototype.hasOwnProperty.call(HPNY_CONTENT, value)
}

const Hpny = () => {
	const { name } = useParams<{ name: string }>()
	const [isMobile, setIsMobile] = useState<boolean>(false)

	const receiverKey = name ?? ''

	if (!isHpnyReceiver(receiverKey)) {
		return <Navigate to="/" replace />
	}

	const content = useMemo(() => HPNY_CONTENT[receiverKey], [receiverKey])

	useEffect(() => {
		document.title = `Happy New Year, ${content.receiverDisplayName}`
	}, [content.receiverDisplayName])

	useEffect(() => {
		const checkMobile = () => {
			setIsMobile(window.innerWidth < 640)
		}

		checkMobile()
		window.addEventListener('resize', checkMobile)
		return () => window.removeEventListener('resize', checkMobile)
	}, [])

	return (
		<div className="fixed inset-0 z-50 bg-gradient-to-br from-slate-950 via-slate-900 to-black text-white">
			<div className="h-full w-full flex items-center justify-center p-6">
				<div className="w-full max-w-4xl flex flex-col items-center gap-6">
					{isMobile ? <HpnyCardMobile content={content} /> : <HpnyCard content={content} />}

					<p className="text-xs text-white/60 text-center max-w-md">just tap, tap, tap...</p>
				</div>
			</div>
		</div>
	)
}

export default Hpny
