import { Navigate, useParams } from 'react-router-dom'
import { useEffect, useMemo, useState } from 'react'
import HpnyCard from '../../components/HpnyCard/HpnyCard'
import HpnyCardMobile from '../../components/HpnyCard/HpnyCardMobile'
import type { HpnyCardContent } from './hpnyContent'

// Encoded HPNY_CONTENT (base64)
const ENCODED_CONTENT =
	'eyI0aG00ZC0yMDI2Ijp7InJlY2VpdmVySWQiOiI0aG00ZC0yMDI2IiwicmVjZWl2ZXJEaXNwbGF5TmFtZSI6IkFobWFkIiwiY292ZXJUaXRsZSI6IkhhcHB5IE5ldyBZZWFyISIsImNvdmVyU3VidGl0bGUiOiJBIHNtYWxsIGNhcmQganVzdCBmb3IgeW91IiwiaW5zaWRlVGl0bGUiOiIiLCJpbnNpZGVCb2R5IjoiRGVhciBBaG1hZCxcblxuSGFwcHkgbmV3IHllYXIhIVxuXG5JIHdpc2ggeW91IGFub3RoZXIgeWVhciBmdWxsIG9mIGhlYWx0aCBhbmQgaGFwcGluZXNzIHdpdGggeW91ciBmYW1pbHkuXG5cbkkgYWxzbyB3YW50IHRvIHRha2UgdGhpcyBvcHBvcnR1bml0eSB0byB0aGFuayB5b3UgZm9yIHlvdXIgc3VwcG9ydCB3aXRoIE9ESSBhbmQgYSBsb3QgbW9yZSBhdCB3b3JrLiBIZXJlIHRvIGFub3RoZXIgYXdlc29tZSB5ZWFyIHdvcmtpbmcgdG9nZXRoZXIg8J+knPCfpJshIiwic2lnbmF0dXJlIjoiQmVzdCIsImltYWdlcyI6WyJmdy5qcGciLCJncmlmMS5qcGciXX0sIkRpa3NoYTI2Ijp7InJlY2VpdmVySWQiOiJEaWtzaGEiLCJyZWNlaXZlckRpc3BsYXlOYW1lIjoiRGlrc2hhIiwiY292ZXJUaXRsZSI6IkhhcHB5IE5ldyBZZWFyISIsImNvdmVyU3VidGl0bGUiOiJBIHNtYWxsIGNhcmQganVzdCBmb3IgeW91IiwiaW5zaWRlVGl0bGUiOiIiLCJpbnNpZGVCb2R5IjoiRGVhciBEaWtzaGEsXG5cbkhhcHB5IG5ldyB5ZWFyISFcblxuSSB3aXNoIHlvdSBhbm90aGVyIHllYXIgZnVsbCBvZiBoZWFsdGggYW5kIGhhcHBpbmVzcyB3aXRoIHlvdXIgaHViYnkgYW5kIGZhbWlseS5cblxuVGhhbmsgeW91IGZvciBoZWxwaW5nIG1lIHBlcnNvbmFsbHkgYW5kIHRoZSB0ZWFtIG9uIG11bHRpcGxlIGZyb250cy4gRnJvbSBqdXN0IHNob3J0IDMgbW9udGhzLCBJJ3ZlIHNlZW4geW91IGJyaW5nIGEgdG9uIG9mIHZhbHVlcyB0byB0aGUgdGVhbSBhbmQgSSBkbyBhZG1pcmUgdGhhdC4gSGVyZSB0byBhbm90aGVyIGF3ZXNvbWUgeWVhciB3b3JraW5nIHRvZ2V0aGVyIPCfpJzwn6SbISIsInNpZ25hdHVyZSI6IkJlc3QiLCJpbWFnZXMiOlsiZncuanBnIiwiZ3JpZjEuanBnIl19LCJhbHYxbiI6eyJyZWNlaXZlcklkIjoiYWx2MW4iLCJyZWNlaXZlckRpc3BsYXlOYW1lIjoiQWx2aW4iLCJjb3ZlclRpdGxlIjoiSGFwcHkgTmV3IFllYXIhIiwiY292ZXJTdWJ0aXRsZSI6IkEgc21hbGwgY2FyZCBqdXN0IGZvciB5b3UiLCJpbnNpZGVUaXRsZSI6IiIsImluc2lkZUJvZHkiOiJEZWFyIEFsdmluLFxuXG5IYXBweSBuZXcgeWVhciEhXG5cbkkgd2lzaCB5b3UgYW5vdGhlciB5ZWFyIGZ1bGwgb2YgaGVhbHRoIGFuZCBoYXBwaW5lc3Mgd2l0aCB5b3VyIGZhbWlseS5cblxuSSB3YW50IHRvIHRha2UgdGhpcyBvcHBvcnR1bml0eSB0byB0aGFuayB5b3UgZm9yIHRydXN0aW5nIG1lLCBsZXR0aW5nIG1lIGJlIGEgcGFydCBvZiB0aGlzIGFtYXppbmcgdGVhbSBhbmQgZm9yIHRoZSB0cmVtZW5kb3VzIHN1cHBvcnQgeW91J3ZlIGJlZW4gcHJvdmlkaW5nLiBIZXJlIHRvIGFub3RoZXIgYXdlc29tZSB5ZWFyIHdvcmtpbmcgdG9nZXRoZXIg8J+knPCfpJshIiwic2lnbmF0dXJlIjoiQmVzdCIsImltYWdlcyI6WyJmdy5qcGciLCJncmlmMS5qcGciXX0sImplc3NpZTIwMjYiOnsicmVjZWl2ZXJJZCI6Implc3NpZTIwMjYiLCJyZWNlaXZlckRpc3BsYXlOYW1lIjoiSmVzc2llIiwiY292ZXJUaXRsZSI6IkhhcHB5IE5ldyBZZWFyISIsImNvdmVyU3VidGl0bGUiOiJBIHNtYWxsIGNhcmQganVzdCBmb3IgeW91IiwiaW5zaWRlVGl0bGUiOiIiLCJpbnNpZGVCb2R5IjoiRGVhciBKZXNzaWUsXG5cbkhhcHB5IG5ldyB5ZWFyISFcblxuSSB3aXNoIHlvdSBhbm90aGVyIHllYXIgZnVsbCBvZiBoZWFsdGggYW5kIGhhcHBpbmVzcyB3aXRoIHlvdXIgYmlnIGZhbWlseS5cblxuSSB3YW50IHRvIHRha2UgdGhpcyBvcHBvcnR1bml0eSB0byB0aGFuayB5b3UgZm9yIHlvdXIgbGVhZGVyc2hpcCwgZm9yIHRydXN0aW5nIG1lIGFuZCBsZXR0aW5nIG1lIGJlIGEgcGFydCBvZiB0aGUgdGVhbS5cblxuSGVyZSB0byBhIG5ldyBmcnVpdGZ1bCB5ZWFyISIsInNpZ25hdHVyZSI6IkJlc3QiLCJpbWFnZXMiOlsiZncuanBnIiwiZ3JpZjEuanBnIl19LCJhbnRob255MTI2Ijp7InJlY2VpdmVySWQiOiJhbnRob255MTI2IiwicmVjZWl2ZXJEaXNwbGF5TmFtZSI6IkFudGhvbnkiLCJjb3ZlclRpdGxlIjoiSGFwcHkgTmV3IFllYXIhIiwiY292ZXJTdWJ0aXRsZSI6IkEgc21hbGwgY2FyZCBqdXN0IGZvciB5b3UiLCJpbnNpZGVUaXRsZSI6IiIsImluc2lkZUJvZHkiOiJEZWFyIEFudGhvbnksXG5cbkhhcHB5IG5ldyB5ZWFyISFcblxuSSB3aXNoIHlvdSBhbmQgeW91ciBmYW1pbHkgYW5vdGhlciB5ZWFyIGZ1bGwgb2YgaGVhbHRoIGFuZCBoYXBwaW5lc3MuIEFuZCBJIHdpc2ggZXZlcnl0aGluZyB3b3VsZCBnbyB3ZWxsIHdpdGggeW91ciBkYXVnaHRlcidzIHRyZWF0bWVudCwgcGxlYXNlIGxldCBtZSBrbm93IGlmIEkgY2FuIGhlbHAgeW91IGluIGFueSB3YXksIEkgZG8ga25vdyBWaWV0bmFtIGFsc28gaGFzIHZlcnkgaWYgbm90IG1vcmUgY2FwYWJsZSBkb2N0b3JzLlxuXG5BbmQsIHRoYW5rIHlvdSBmb3IgbGVhZGVyc2hpcCwgZm9yIHRydXN0aW5nIG1lIGFuZCBsZXR0aW5nIG1lIGJlIGEgcGFydCBvZiB0aGlzIHdvbmRlcmZ1bCB0ZWFtLiIsInNpZ25hdHVyZSI6IkJlc3QiLCJpbWFnZXMiOlsiZncuanBnIiwiZ3JpZjIuanBnIl19LCJsdWNpdXNDYXAiOnsicmVjZWl2ZXJJZCI6Imx1Y2l1c0NhcCIsInJlY2VpdmVyRGlzcGxheU5hbWUiOiJWaW5oIiwiY292ZXJUaXRsZSI6IkhhcHB5IE5ldyBZZWFyISIsImNvdmVyU3VidGl0bGUiOiJUbyBncmVhdG5lc3MgYW5kIHByb3NwZXJpdHkiLCJpbnNpZGVUaXRsZSI6IiIsImluc2lkZUJvZHkiOiJIZXkgVmluaCxcblxuSGFwcHkgbmV3IHllYXIgdG8geW91IGFuZCB5b3VyIGZhbWlseSFcblxuSSB3aXNoIHlvdSBhbmQgTHVjaXVzIENhcGl0YWwgYW5vdGhlciBwcm9zcGVyb3VzIHllYXIgd2l0aCBncmVhdGVyIGFjaGlldmVtZW50cyBhbmQgc3VjY2Vzc2VzLiBBbmQgdGhhbmsgeW91IGZvciB0aGUgZnJpZW5kc2hpcCwgdGhlIHBhcnRuZXJzaGlwLCB0aGUgY2FyKHMpIGFuZCB3aGF0ZXZlciBlbHNlIHRoZXJlIGlzIVxuXG5KdXN0IGFzIGltcG9ydGFudGx5LCB0YWtlIGdvb2QgY2FyZSBvZiB5b3VyIGhlYWx0aCBhbmQgZXhlcmNpc2UgbW9yZSBzaXIuIiwic2lnbmF0dXJlIjoiQmVzdCIsImltYWdlcyI6WyJ2aW5oMS5qcGciLCJ2aW5oMy5qcGciXX0sIm5hLWNvbS1uYW0iOnsicmVjZWl2ZXJJZCI6Im5hLWNvbS1uYW0iLCJyZWNlaXZlckRpc3BsYXlOYW1lIjoiTmluYSIsImNvdmVyVGl0bGUiOiJIYXBweSBOZXcgWWVhciEiLCJjb3ZlclN1YnRpdGxlIjoiZ+G7rWkgdOG7m2kgY8ahbSBu4bqvbSBj4bunYSBhbmgiLCJpbnNpZGVUaXRsZSI6IiIsImluc2lkZUJvZHkiOiJD4bulYyBjxqFtIG7huq9tIGl1IGThuqV1IGPhu6dhIGFuaCxcblxuSGFwcHkgbmV3IHllYXIgYW5kIGhhcHB5IDEgeWVhciBhcm91bmQgdGhlIHN1biB3aXRoIHlvdSFcblxuVGhpcyB5ZWFyLCB3ZSBib3RoIHdpbGwgbmVlZCB0byBjaGFuZ2UgZm9yIHRoZSBiZXR0ZXIuIEkgd2lsbCBtYWtlIGEgcHJvbWlzZSB0byB5b3UgdGhhdCB3ZSB3aWxsIHNwZW5kIG1vcmUgcXVhbGl0eSB0aW1lIHRvZ2V0aGVyLCBuaWdodC10aW1lIHdpdGhvdXQgc29jaWFsIG1lZGlhIGRpc3J1cHRpb24sIGdyb3cgc21hcnRlciBlbW90aW9uYWxseSBhbmQgaW50ZWxsaWdlbnRseSwgd2VhciBjb29sLWFzcyBvdXRmaXRzIGFuZCBnbyBvbiBhIGRhdGUtbmlnaHQgZXZlcnkgbW9udGguIFRoYXQncyB0aGUgbGVhc3QgSSBjYW4gZG8uXG5cbkkgb25seSB3aXNoIHRoYXQgdGhpcyB5ZWFyLCB5b3Ugd2lsbCBoYXZlIG1vcmUgYXVkYWNpdHkgdG8gc3BlYWsgd2hhdCB5b3UgdGhpbmssIGRvIHdoYXQgeW91IHdhbnQsIGdldCB3aGF0IHlvdSBob3BlIGZvciBhbmQgdGFrZSBhY3Rpb24gdG8gYWNoaWV2ZSB5b3VyIGdvYWxzLiBNb3N0IGltcG9ydGFudGx5LCB0aGluayBhYm91dCB3aGF0IHlvdSB3YW50IGluIGxpZmUgb3IgdGhpcyB5ZWFyLCB5b3UncmUgeW91bmcgc28gY2hlcmlzaCBldmVyeSBwaWVjZSBvZiB0aW1lIHlvdSBoYXZlIGFuZCBtYWtlIHRoZSBtb3N0IG9mIGl0LiBJJ20gYSBndXkgc28gSSdtIHNvIGxvZ2ljYWwgYWJvdXQgdGhlc2Ugc3R1ZmZzLCBJIHBsYW4gYW5kIGNhbGN1bGF0ZSBhIGxvdCwgbWF5YmUgYSBiaXQgb2YgdGhhdCAobG9naWNhbCwgcGxhbm5pbmcsIGNhbGN1bGF0aW5nKSB3aWxsIGRvIGdvb2QgZm9yIHlvdXIgbGlmZS4gU28sIGFuc3dlciB0aGlzOiBXaGF0IGRvIHlvdSB3YW50IGZvciB5b3Vyc2VsZiB0aGlzIHllYXI/XG5cblRoYW5rIHlvdSBmb3IgYnJpbmcgc21pbGVzIHRvIG15IGZhY2UgYWxsIHRoZSB0aW1lLiIsInNpZ25hdHVyZSI6IkkgbG92ZSB5b3Ug8J+SmSIsImltYWdlcyI6WyJuYTEuanBnIiwibmEyLmpwZyJdfSwiYWw0biI6eyJyZWNlaXZlcklkIjoiYWw0biIsInJlY2VpdmVyRGlzcGxheU5hbWUiOiJBbGFuIiwiY292ZXJUaXRsZSI6IkhhcHB5IE5ldyBZZWFyISIsImNvdmVyU3VidGl0bGUiOiJ0byBteSBicm90aGVyIiwiaW5zaWRlVGl0bGUiOiIiLCJpbnNpZGVCb2R5IjoiRGVhciBIb2FuZyBBbmgsXG5cbkhhcHB5IG5ldyB5ZWFyIGFuZCB3ZWxjb21lIHlvdSB0byB0aGUgYWdlIG9mIGluZGVwZW5kZW5jZSAoMTh5bykhXG5cbllvdSBhcmUgZWFybmluZyB5b3VyIG93biBtb25leSBub3csIEknbSBzbyBoYXBweSEgTGlmZSBpcyBzdGlsbCBsb25nIGJ1dCBtYWtlIHN1cmUgeW91IHVzZSBpdCB3aXNlbHksIG1ha2UgcGxhbnMgdG8gdHJhdmVsIGFyb3VuZCBtb3JlIChhdCBsZWFzdCAxIG5lYXIgYW5kIDEgZmFyIHBsYWNlcyBhIHllYXIpIGFzIHRoaXMgaXMgd2hhdCBJIHdpc2ggSSBoYWQgZG9uZSBpbiB5b3VyIGFnZS4gSSB0aG91Z2h0IHdoZW4gSSBoYXZlIG1vbmV5LCBJIHdpbGwgdHJhdmVsIG1vcmUgYnV0IEkgY2FuIGhhcmRseSBmaW5kIHRoZSB0aW1lLiBTbyB5ZWEuLi4gbWFrZSBwbGFuIGZvciB0cmF2ZWxpbmcuXG5cblRyYXZlbGluZyBpcyBvbmUgb2YgdGhlIGNoZWFwIGFjdGlvbnMgdGhhdCB5b3UgY2FuIGRvIHRvIGdldCBvdXQgb2YgeW91ciBjb21mb3J0IHpvbmVzIC0gdGhlIGhvdXNlIGFuZCB0aGUgY2l0eSB5b3Uga25vdyB0b28gd2VsbC4gU28gZG8gdGhhdCBtb3JlLCBJIHRoaW5rIHRoYXQgd2lsbCBldmVudHVhbGx5IGZvcm0gYSBoYWJpdCBvZiBnZXR0aW5nIG91dCBvZiB5b3VyIGNvbWZvcnQgem9uZXMgc29tZWhvdy5cblxuWW91J3ZlIG1hZGUgZnJpZW5kcyBmYXN0ZXIgdGhhbiBtZSBhbmQgd2hhdCBJIHRob3VnaHQuSSBoYXZlIG9ic2VydmVkIHlvdSBncm93IGFuZCBhZGFwdCB2ZXJ5IHdlbGwgdG8gQXVzc2llIGFuZCBJIGhhdmUgbm8gZG91YnQgdGhhdCB5b3VyIHBlcnNvbmFsaXR5IGFuZCB5b3VyIGludGVsbGlnZW5jZSB3aWxsIHRha2UgeW91IGZhciBpbiBBdXNzaWUuIEFpbSBoaWdoIGFuZCwgd2hhdGV2ZXIgZnJpZW5kcyBhbmQgY29tcGFuaWVzIHlvdSBhcmUgaW4sIG1ha2Ugc3VyZSB0aGV5IGFyZSBhIGdvb2QgZml0IGZvciB5b3UgKEkgc2F5IHRoaXMgYmVjYXVzZSBJIGhhdmUgYmVlbiBpbiBtZWRpb2NyZSBjb21wYW5pZXMgYW5kIHlvdSBkb24ndCBiZWxvbmcgdG8gdGhvc2UpLlxuXG5CZSBodW5ncnksIGJyb3RoZXIuIiwic2lnbmF0dXJlIjoiQmVzdCIsImltYWdlcyI6WyJoYTEuanBnIiwiaGEyLmpwZyJdfSwibW9tIjp7InJlY2VpdmVySWQiOiJtb20iLCJyZWNlaXZlckRpc3BsYXlOYW1lIjoiTW9tIiwiY292ZXJUaXRsZSI6IkhhcHB5IE5ldyBZZWFyISIsImNvdmVyU3VidGl0bGUiOiJ0byBteSBtb20iLCJpbnNpZGVUaXRsZSI6IiIsImluc2lkZUJvZHkiOiJEZWFyIE1vbSxcblxuSSB3aXNoIHlvdSBhbm90aGVyIHllYXIgZnVsbCBvZiBoZWFsdGggYW5kIGhhcHBpbmVzcyB3aXRoIHlvdXIgZmFtaWx5LlxuXG5JIHdhbnQgdG8gdGFrZSB0aGlzIG9wcG9ydHVuaXR5IHRvIHRoYW5rIHlvdSBmb3IgeW91ciBzdXBwb3J0IHdpdGggT0RJIGFuZCBhIGxvdCBtb3JlIGF0IHdvcmsuIEhlcmUgdG8gYW5vdGhlciBhd2Vzb21lIHllYXIgd29ya2luZyB0b2dldGhlciDwn6Sc8J+kmyEiLCJzaWduYXR1cmUiOiJCZXN0In0sImRhZCI6eyJyZWNlaXZlcklkIjoiZGFkIiwicmVjZWl2ZXJEaXNwbGF5TmFtZSI6IkRhZCIsImNvdmVyVGl0bGUiOiJIYXBweSBOZXcgWWVhciEiLCJjb3ZlclN1YnRpdGxlIjoidG8gbXkgZGFkIiwiaW5zaWRlVGl0bGUiOiIiLCJpbnNpZGVCb2R5IjoiRGVhciBEYWQsXG5cbkkgd2lzaCB5b3UgYW5vdGhlciB5ZWFyIGZ1bGwgb2YgaGVhbHRoIGFuZCBoYXBwaW5lc3Mgd2l0aCB5b3VyIGZhbWlseS5cblxuSSB3YW50IHRvIHRha2UgdGhpcyBvcHBvcnR1bml0eSB0byB0aGFuayB5b3UgZm9yIHlvdXIgc3VwcG9ydCB3aXRoIE9ESSBhbmQgYSBsb3QgbW9yZSBhdCB3b3JrLiBIZXJlIHRvIGFub3RoZXIgYXdlc29tZSB5ZWFyIHdvcmtpbmcgdG9nZXRoZXIg8J+knPCfpJshIiwic2lnbmF0dXJlIjoiQmVzdCJ9LCJyb2xhbmQiOnsicmVjZWl2ZXJJZCI6InJvbGFuZCIsInJlY2VpdmVyRGlzcGxheU5hbWUiOiJNaW5oIiwiY292ZXJUaXRsZSI6IkhhcHB5IE5ldyBZZWFyISIsImNvdmVyU3VidGl0bGUiOiJ0byBteSBmaXJzdCBCcmlzc2llIGZyaWVuZCIsImluc2lkZVRpdGxlIjoiIiwiaW5zaWRlQm9keSI6IkRlYXIgTWluaCxcblxuSSB3aXNoIHlvdSBhbm90aGVyIHllYXIgZnVsbCBvZiBoZWFsdGggYW5kIGhhcHBpbmVzcyB3aXRoIHlvdXIgZmFtaWx5LlxuXG5JIHdhbnQgdG8gdGFrZSB0aGlzIG9wcG9ydHVuaXR5IHRvIHRoYW5rIHlvdSBmb3IgeW91ciBzdXBwb3J0IHdpdGggT0RJIGFuZCBhIGxvdCBtb3JlIGF0IHdvcmsuIEhlcmUgdG8gYW5vdGhlciBhd2Vzb21lIHllYXIgd29ya2luZyB0b2dldGhlciDwn6Sc8J+kmyEiLCJzaWduYXR1cmUiOiJCZXN0In0sIm1pbmhkYW5nIjp7InJlY2VpdmVySWQiOiJtaW5oZGFuZyIsInJlY2VpdmVyRGlzcGxheU5hbWUiOiJEYW5nIiwiY292ZXJUaXRsZSI6IkhhcHB5IE5ldyBZZWFyISIsImNvdmVyU3VidGl0bGUiOiJ0byBteSBmaXJzdCBCcmlzc2llIGZyaWVuZCIsImluc2lkZVRpdGxlIjoiIiwiaW5zaWRlQm9keSI6IkRlYXIgRGFuZyxcblxuSSB3aXNoIHlvdSBhbm90aGVyIHllYXIgZnVsbCBvZiBoZWFsdGggYW5kIGhhcHBpbmVzcyB3aXRoIHlvdXIgZmFtaWx5LlxuXG5JIHdhbnQgdG8gdGFrZSB0aGlzIG9wcG9ydHVuaXR5IHRvIHRoYW5rIHlvdSBmb3IgeW91ciBzdXBwb3J0IHdpdGggT0RJIGFuZCBhIGxvdCBtb3JlIGF0IHdvcmsuIEhlcmUgdG8gYW5vdGhlciBhd2Vzb21lIHllYXIgd29ya2luZyB0b2dldGhlciDwn6Sc8J+kmyEiLCJzaWduYXR1cmUiOiJCZXN0In0sImdvd3JpIjp7InJlY2VpdmVySWQiOiJnb3dyaSIsInJlY2VpdmVyRGlzcGxheU5hbWUiOiJHb3dyaSIsImNvdmVyVGl0bGUiOiJIYXBweSBOZXcgWWVhciEiLCJjb3ZlclN1YnRpdGxlIjoiQSBzbWFsbCBjYXJkIGp1c3QgZm9yIHlvdSIsImluc2lkZVRpdGxlIjoiIiwiaW5zaWRlQm9keSI6IkRlYXIgR293cmksXG5cbkhhcHB5IE5ldyBZZWFyIVxuXG4iLCJzaWduYXR1cmUiOiJCZXN0In0sImJvbmdnb24iOnsicmVjZWl2ZXJJZCI6ImJvbmdnb24iLCJyZWNlaXZlckRpc3BsYXlOYW1lIjoiYm9uZ2dvbiIsImNvdmVyVGl0bGUiOiJIYXBweSBOZXcgWWVhciEiLCJjb3ZlclN1YnRpdGxlIjoiQSBzbWFsbCBjYXJkIGp1c3QgZm9yIHlvdSIsImluc2lkZVRpdGxlIjoiIiwiaW5zaWRlQm9keSI6IkRlYXIgTmhpLFxuXG5JIHdpc2ggeW91IGFub3RoZXIgeWVhciBmdWxsIG9mIGhlYWx0aCBhbmQgaGFwcGluZXNzIHdpdGggeW91ciBmYW1pbHkuXG5cbkkgd2FudCB0byB0YWtlIHRoaXMgb3Bwb3J0dW5pdHkgdG8gdGhhbmsgeW91IGZvciB5b3VyIHN1cHBvcnQgd2l0aCBPREkgYW5kIGEgbG90IG1vcmUgYXQgd29yay4gSGVyZSB0byBhbm90aGVyIGF3ZXNvbWUgeWVhciB3b3JraW5nIHRvZ2V0aGVyIPCfpJzwn6SbISIsInNpZ25hdHVyZSI6IkJlc3QifSwiYmE0NHkiOnsicmVjZWl2ZXJJZCI6ImJhNDR5IiwicmVjZWl2ZXJEaXNwbGF5TmFtZSI6ImJhNDR5IiwiY292ZXJUaXRsZSI6IkhhcHB5IE5ldyBZZWFyISIsImNvdmVyU3VidGl0bGUiOiJPcGVuIG1lIiwiaW5zaWRlVGl0bGUiOiJDaGVlcnMiLCJpbnNpZGVCb2R5IjoiRGVhciBiYTQ0eSxcblxuVE9ETzogV3JpdGUgeW91ciBwZXJzb25hbCBtZXNzYWdlIGhlcmUuXG5cblRoYW5rcyBmb3IgYmVpbmcgcGFydCBvZiBteSB5ZWFyIOKAlCBsZXQncyBtYWtlIHRoZSBuZXh0IG9uZSBldmVuIGJldHRlci5cblxuVE9ETzogQWRkIGEgc2hvcnQgd2lzaCB0aGF0IGZpdHMgeW91ciBmcmllbmRzaGlwLlxuXG5Nb3JlIGxhdWdodGVyLCBtb3JlIGdyb3d0aCwgYW5kIG1vcmUgZ29vZCBtb21lbnRzLiIsInNpZ25hdHVyZSI6IuKAlCBSb2RvIn0sIm9wdXNtYXhpbXVzIjp7InJlY2VpdmVySWQiOiJvcHVzbWF4aW11cyIsInJlY2VpdmVyRGlzcGxheU5hbWUiOiJvcHVzbWF4aW11cyIsImNvdmVyVGl0bGUiOiJIYXBweSBOZXcgWWVhciEiLCJjb3ZlclN1YnRpdGxlIjoiRnJvbSBtZSB0byB5b3UiLCJpbnNpZGVUaXRsZSI6IkxldCdzIGdvIiwiaW5zaWRlQm9keSI6IkRlYXIgb3B1c21heGltdXMsXG5cbldpc2hpbmcgeW91IG1vbWVudHVtLCBjbGFyaXR5LCBhbmQgYSB5ZWFyIHRoYXQgZmVlbHMgbGlrZSBhIGJpZyBzdGVwIGZvcndhcmQuXG5cbk1heSAyMDI2IGJyaW5nIHlvdSBib2xkIGlkZWFzIGFuZCBjYWxtIGV4ZWN1dGlvbi4iLCJzaWduYXR1cmUiOiLigJQgUm9kbyJ9LCJTdGV2ZSI6eyJyZWNlaXZlcklkIjoiU3RldmUiLCJyZWNlaXZlckRpc3BsYXlOYW1lIjoiU3RldmUiLCJjb3ZlclRpdGxlIjoiSGFwcHkgTmV3IFllYXIhIiwiY292ZXJTdWJ0aXRsZSI6IkEgc21hbGwgY2FyZCBqdXN0IGZvciB5b3UiLCJpbnNpZGVUaXRsZSI6IiIsImluc2lkZUJvZHkiOiJEZWFyIFN0ZXZlLFxuXG5JIHdpc2ggeW91IGFub3RoZXIgeWVhciBmdWxsIG9mIGhlYWx0aCBhbmQgaGFwcGluZXNzIHdpdGggeW91ciBmYW1pbHkuXG5cbkkgd2FudCB0byB0YWtlIHRoaXMgb3Bwb3J0dW5pdHkgdG8gdGhhbmsgeW91IGZvciB5b3VyIHN1cHBvcnQgd2l0aCBPREkgYW5kIGEgbG90IG1vcmUgYXQgd29yay4gSGVyZSB0byBhbm90aGVyIGF3ZXNvbWUgeWVhciB3b3JraW5nIHRvZ2V0aGVyIPCfpJzwn6SbISIsInNpZ25hdHVyZSI6IkJlc3QifX0='

// Decode and parse the content
const decodeContent = (): Record<string, HpnyCardContent> => {
	try {
		const base64Decoded = atob(ENCODED_CONTENT)
		// Convert binary string to Uint8Array for proper UTF-8 decoding
		const bytes = new Uint8Array(base64Decoded.length)
		for (let i = 0; i < base64Decoded.length; i++) {
			bytes[i] = base64Decoded.charCodeAt(i)
		}
		// Decode UTF-8 properly to handle emojis
		const decoded = new TextDecoder('utf-8').decode(bytes)
		// Validate the decoded string doesn't contain unescaped control characters
		const parsed = JSON.parse(decoded) as Record<string, HpnyCardContent>
		return parsed
	} catch (error) {
		console.error('Failed to decode HPNY_CONTENT:', error)
		if (error instanceof SyntaxError) {
			console.error('This is likely due to unescaped control characters in the JSON.')
			console.error('Please regenerate the encoded content using: node encode-content.cjs')
		}
		return {}
	}
}

const HPNY_CONTENT = decodeContent()

const isHpnyReceiver = (value: string): value is string => {
	return Object.prototype.hasOwnProperty.call(HPNY_CONTENT, value)
}

const Hpny = () => {
	const { name } = useParams<{ name: string }>()
	const [isMobile, setIsMobile] = useState<boolean>(false)

	const receiverKey = name ?? ''

	if (!isHpnyReceiver(receiverKey)) {
		return <Navigate to="/" replace />
	}

	const content = useMemo(() => HPNY_CONTENT[receiverKey], [receiverKey])

	useEffect(() => {
		document.title = `Happy New Year, ${content.receiverDisplayName}`
	}, [content.receiverDisplayName])

	useEffect(() => {
		const checkMobile = () => {
			setIsMobile(window.innerWidth < 640)
		}

		checkMobile()
		window.addEventListener('resize', checkMobile)
		return () => window.removeEventListener('resize', checkMobile)
	}, [])

	return (
		<div className="fixed inset-0 z-50 bg-gradient-to-br from-slate-950 via-slate-900 to-black text-white">
			<div className="h-full w-full flex items-center justify-center p-6">
				<div className="w-full max-w-4xl flex flex-col items-center gap-6">
					{isMobile ? <HpnyCardMobile content={content} /> : <HpnyCard content={content} />}

					<p className="text-xs text-white/60 text-center max-w-md">just tap, tap, tap...</p>
				</div>
			</div>
		</div>
	)
}

export default Hpny
